// src/main/java/org/shop/beautyportal/saleschannels/adapters/in/ui-core/src/components/atoms/select/Select.svelte
<script>
    export let value = '';
    export let variant = 'primary';
    export let size = '';
    export let invalid = false;
    export let disabled = false;
    export let name;
    export let id;

    export let items = [];

    $: cls =
        `select select--${variant}` +
        (size ? ` select--${size}` : '') +
        (invalid ? ' is-invalid' : '');
</script>

<style lang="scss">
  @import "select.scss";
</style>

<select
        class={cls}
        bind:value={value}
        {disabled}
        {name}
        {id}
        aria-invalid={invalid}
>
    {#if items.length}
        {#each items as it}
            {#if typeof it === 'object'}
                <option value={it.value}>{it.label ?? it.value}</option>
            {:else}
                <option value={it}>{it}</option>
            {/if}
        {/each}
    {:else}
        <slot />
    {/if}
</select>

// frontend/src/components/atoms/Select/Select.jsx
import React from 'react';
import selectPropTypes from './Select.propTypes';
import './select.scss';

const Select = ({
                    options,
                    value,
                    onChange,
                    disabled,
                    name,
                    id,
                }) => {
    return (
        <select
            className="select"
            value={value}
            onChange={onChange}
            disabled={disabled}
            name={name}
            id={id}
        >
            {options.map((opt) => (
                <option key={opt.value} value={opt.value}>
                    {opt.label}
                </option>
            ))}
        </select>
    );
};

Select.propTypes = selectPropTypes;

export default Select;
